---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/assets/content/blog
  label: Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Authors
- type: document
  path: src/assets/content/data/authors.json
  label: Authors List
upload_dir: src/assets/content/images
public_path: "/src/assets/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
